
function jacobian = f_doubleGaussianVectorJacobian(par,ii,jj)
  jacobian1 = exp( -((ii-par(3)).^2+(jj-par(4)).^2) / (2*par(7).^2));
  jacobian2 = exp( -((ii-par(5)).^2+(jj-par(6)).^2) / (2*par(8).^2));
  jacobian3 = par(1) .* exp( -((ii-par(3)).^2+(jj-par(4)).^2) / (2*par(7).^2)) ...
          .* (ii-par(3)) / (par(7).^2);
  jacobian4 = par(1).*exp( -((ii-par(3)).^2+(jj-par(4)).^2) / (2*par(7).^2)) ...
          .* (jj-par(4)) / (par(7).^2);
  jacobian5 = par(2).*exp( -((ii-par(5)).^2+(jj-par(6)).^2) / (2*par(8).^2)) ...
          .* (ii-par(5)) / (par(8).^2);
  jacobian6 = par(2).*exp( -((ii-par(5)).^2+(jj-par(6)).^2) / (2*par(8).^2)) ...
          .* (jj-par(6)) / (par(8).^2);
  jacobian7 = par(1).*exp( -((ii-par(3)).^2+(jj-par(4)).^2) / (2*par(7).^2)) ...
          .* ((ii-par(3)).^2+(jj-par(4)).^2) / (par(7).^3);
  jacobian8 = par(2).*exp( -((ii-par(5)).^2+(jj-par(6)).^2) / (2*par(8).^2)) ...
          .* ((ii-par(5)).^2+(jj-par(6)).^2) / (par(8).^3);
 
  jacobian = [reshape(jacobian1,[],1) reshape(jacobian2,[],1) ...
      reshape(jacobian3,[],1) reshape(jacobian4,[],1) ...
      reshape(jacobian5,[],1) reshape(jacobian6,[],1) ...
      reshape(jacobian7,[],1) reshape(jacobian8,[],1)];
